---
title: "Writing Functions"
output: github_document
---

```{r, include = FALSE, message = FALSE, warning = FALSE}
library(tidyverse)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


## Lists

```{r}
vec_numeric = 5:8
vec_char = c("My", "name", "is", "Jeff")
vec_logical = c(TRUE, FALSE, TRUE, TRUE)
```

Let's look at a list

```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(100))
)
```


Accessing list items

```{r}
l$vec_numeric

l[[3]]

l[["mat"]]
```


Let's write a `for` loop to take the mean and SD

```{r}
list_norm =
  list(
    a = rnorm(20, 5, 4),
    b = rnorm(20, -12, 3),
    c = rnorm(20, 17, .4),
    d = rnorm(20, 100, 1)
  )
```

Here's my function

```{r}
mean_and_sd = function(x) {

  if (!is.numeric(x)) {
    stop("Z scores only work for numbers")
  }
  
  if (length(x) < 3) {
    stop("Z scores really only work if you have three or more numbers")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
  
}
```

Let's try to make this work

```{r}
mean_and_sd(list_norm[[1]])
mean_and_sd(list_norm[[2]])
mean_and_sd(list_norm[[3]])
mean_and_sd(list_norm[[4]])
```

Let's try a `for` loop instead

```{r}
output = vector("list", length = 4)

output[[1]] = mean_and_sd(list_norm[[1]])

for (i in 1:4) {
  
  output[[i]] = mean_and_sd(list_norm[[i]])
  
}

output
```


## `map`

```{r}
map(list_norm, mean_and_sd)
```

what about other functions ...

```{r}
map(list_norm, median)
map(list_norm, var)
map(list_norm, summary)
```

map variants

```{r}
map_dbl(list_norm, median)
output = map_df(list_norm, mean_and_sd)
```


## list columns

```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    norm = list_norm
  )

listcol_df[["norm"]]

map(listcol_df[["norm"]], mean_and_sd)
```

Can we add list columns and then what

```{r}
listcol_df %>% 
  mutate(
    m_sd = map(norm, mean_and_sd)
  )

listcol_df %>% 
  mutate(
    m_sd = map_df(norm, mean_and_sd)
  ) %>% 
  select(-norm)
```

## Something more realistic

```{r}

```

